version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: bitsperity-beacon_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  web:
    image: bitsperity/beacon:latest
    user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/logs:/app/logs
    environment:
      # Beacon Configuration
      BEACON_PORT: 8000
      BEACON_MONGODB_URL: ${BEACON_MONGODB_URL:-mongodb://umbrel:umbrel@bitsperity-mongodb_mongodb_1:27017/}
      BEACON_LOG_LEVEL: ${LOG_LEVEL:-INFO}
      BEACON_TTL_CLEANUP_INTERVAL: ${TTL_CLEANUP_INTERVAL:-30}
      BEACON_DEFAULT_TTL: ${DEFAULT_TTL:-300}
      
      # mDNS Configuration
      MDNS_DOMAIN: ${MDNS_DOMAIN:-local}
      MDNS_INTERFACE: ${MDNS_INTERFACE:-}
      
      # Umbrel Environment Variables
      DEVICE_HOSTNAME: $DEVICE_HOSTNAME
      DEVICE_DOMAIN_NAME: $DEVICE_DOMAIN_NAME
      APP_HIDDEN_SERVICE: $APP_HIDDEN_SERVICE
      APP_PASSWORD: $APP_PASSWORD
      APP_SEED: $APP_SEED 