version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: bitsperity-beacon_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  web:
    build:
      context: .
      dockerfile: Dockerfile.avahi
    # image: bitsperity/beacon:avahi-latest
    init: true
    restart: on-failure
    stop_grace_period: 1m
    # Privileged mode für Avahi-Daemon
    privileged: true
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/logs:/app/logs
      # D-Bus und Avahi Sockets vom Host
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon:/var/run/avahi-daemon
      # Für mDNS Multicast
      - /dev/net/tun:/dev/net/tun
    environment:
      # Beacon Configuration
      BEACON_PORT: 80
      BEACON_MONGODB_URL: ${BEACON_MONGODB_URL:-mongodb://umbrel:umbrel@bitsperity-mongodb_mongodb_1:27017/}
      BEACON_LOG_LEVEL: ${LOG_LEVEL:-INFO}
      BEACON_TTL_CLEANUP_INTERVAL: ${TTL_CLEANUP_INTERVAL:-30}
      BEACON_DEFAULT_TTL: ${DEFAULT_TTL:-300}
      
      # mDNS Configuration
      MDNS_DOMAIN: ${MDNS_DOMAIN:-local}
      MDNS_INTERFACE: ${MDNS_INTERFACE:-}
      
      # Avahi Configuration
      AVAHI_ENABLE: "true"
      
      # Umbrel Environment Variables
      DEVICE_HOSTNAME: $DEVICE_HOSTNAME
      DEVICE_DOMAIN_NAME: $DEVICE_DOMAIN_NAME
      APP_HIDDEN_SERVICE: $APP_HIDDEN_SERVICE
      APP_PASSWORD: $APP_PASSWORD
      APP_SEED: $APP_SEED 