version: "3.7"

services:
  app_proxy:
    environment:
      # bitsperity-beacon_beacon-api_1
      APP_HOST: bitsperity-beacon_beacon-api_1
      APP_PORT: 8080

  beacon-api:
    image: bitsperity/beacon:latest
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/logs:/app/logs
    environment:
      # Beacon Configuration
      BEACON_PORT: 8000
      BEACON_MONGODB_URL: ${BEACON_MONGODB_URL:-mongodb://umbrel:umbrel@umbrel.local:27017/beacon}
      BEACON_LOG_LEVEL: ${LOG_LEVEL:-INFO}
      BEACON_TTL_CLEANUP_INTERVAL: ${TTL_CLEANUP_INTERVAL:-30}
      BEACON_DEFAULT_TTL: ${DEFAULT_TTL:-300}
      
      # mDNS Configuration
      MDNS_DOMAIN: ${MDNS_DOMAIN:-local}
      MDNS_INTERFACE: ${MDNS_INTERFACE:-}
      
      # Umbrel Environment Variables
      DEVICE_HOSTNAME: $DEVICE_HOSTNAME
      DEVICE_DOMAIN_NAME: $DEVICE_DOMAIN_NAME
      APP_HIDDEN_SERVICE: $APP_HIDDEN_SERVICE
      APP_PASSWORD: $APP_PASSWORD
      APP_SEED: $APP_SEED 