version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: bitsperity-homegrow_web_1
      APP_PORT: 3001
      PROXY_AUTH_ADD: 'false'
    container_name: bitsperity-homegrow_app_proxy_1

  web:
    image: bitsperity/homegrow:latest
    user: '1000:1000'
    init: true
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URL=mongodb://umbrel:umbrel@bitsperity-mongodb_mongodb_1:27017/homegrow
      - MQTT_URL=mqtt://mosquitto_broker_1:1883
      - BEACON_URL=http://bitsperity-beacon_web_1:80
      - HOMEGROW_HOST=bitsperity-homegrow_web_1
      - HOMEGROW_PORT=3001
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    container_name: bitsperity-homegrow_web_1

volumes:
  homegrow-v3-data:
    driver: local 