version: '3.8'

services:
  homegrow-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: homegrow_frontend_v3
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
      - API_URL=http://host.docker.internal:4001
    depends_on:
      - homegrow-backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - homegrow-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  homegrow-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: homegrow_backend_v3
    restart: unless-stopped
    network_mode: "host"
    environment:
      - NODE_ENV=development
      - PORT=4001
      - HOST=0.0.0.0
      - MONGODB_URI=mongodb://umbrel:umbrel@192.168.178.124:27017/admin
      - MQTT_HOST=localhost
      - MQTT_PORT=1883
      - JWT_SECRET=${JWT_SECRET:-homegrow-v3-dev-secret}
    volumes:
      - homegrow-v3-data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  homegrow-network:
    driver: bridge
  homegrow_default:
    external: true

volumes:
  homegrow-v3-data:
    driver: local 