version: '3.8'

services:
  bitsperity-homegrow:
    image: bitsperity/homegrow:latest
    container_name: bitsperity-homegrow
    restart: unless-stopped
    stop_grace_period: 1m
    ports:
      - "${APP_HOMEGROW_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URL=mongodb://umbrel:umbrel@bitsperity-mongodb:27017/homegrow
      - MQTT_URL=mqtt://mosquitto:1883
      - BEACON_URL=http://bitsperity-beacon:8097
      - HOMEGROW_HOST=bitsperity-homegrow
      - HOMEGROW_PORT=3000
    depends_on:
      - bitsperity-mongodb
      - bitsperity-beacon
      - mosquitto
    networks:
      - umbrel
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  umbrel:
    external: true

volumes:
  homegrow-v3-data:
    driver: local 