version: '3.8'

services:
  homegrow-app:
    build: .
    container_name: homegrow_v3
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URL=mongodb://bitsperity-mongodb:27017/homegrow
      - MQTT_URL=mqtt://umbrel-mqtt:1883
      - BEACON_URL=http://bitsperity-beacon:8080
      - JWT_SECRET=${JWT_SECRET:-homegrow-v3-production-secret}
      - HOMEGROW_HOST=homegrow-app
      - HOMEGROW_PORT=3000
    depends_on:
      - bitsperity-mongodb
      - bitsperity-beacon
    volumes:
      - homegrow-v3-data:/app/data
    networks:
      - umbrel_main_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  umbrel_main_network:
    external: true

volumes:
  homegrow-v3-data:
    driver: local 