version: "3.7"

services:
  # MongoDB database server
  mongodb:
    image: mongo:7.0
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: umbrel
      MONGO_INITDB_ROOT_PASSWORD: umbrel
      # Add additional MongoDB configuration
      MONGO_INITDB_DATABASE: admin
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    # No port mapping needed - internal service only
    # Data persistence
    volumes:
      - ${APP_DATA_DIR}/data:/data/db
      - ${APP_DATA_DIR}/config:/data/configdb

# Volumes managed by Umbrel via ${APP_DATA_DIR} 